---
name: Devel-TraceDeps
version: v0.0.2
author:
  - 'Eric Wilhelm @ <ewilhelm at cpan dot org>'
abstract: track loaded modules and objects
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-TraceDeps
  homepage: http://scratchcomputing.com/
  license: http://dev.perl.org/licenses/
  repository: http://scratchcomputing.com/svn/Devel-TraceDeps/trunk
requires:
  Class::Accessor::Classy: v0.9.0
build_requires:
  Module::Build: 0.26
  Test::More: 0
provides:
  Devel::TraceDeps:
    file: lib/Devel/TraceDeps.pm
    version: v0.0.2
  Devel::TraceDeps::Scan:
    file: lib/Devel/TraceDeps/Scan.pm
    version: v0.0.2
  Devel::TraceDeps::Scan::Item:
    file: lib/Devel/TraceDeps/Scan.pm
  Devel::TraceDeps::Watch:
    file: lib/Devel/TraceDeps.pm
  Devel::eps:
    file: lib/Devel/eps.pm
    version: v0.0.2
generated_by: Module::Build version 0.280804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
